import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import theme from "@/theme";
import { ThemeProvider } from "@mui/material/styles";
import ReduxProvider from "@/Components/ReduxProvider/ReduxProvider";
import NavBar from "@/Components/NavBar/NavBar";
import { Toaster } from "react-hot-toast";
import ProtectedRoute from "@/ProtectedRoute/ProtectedRoute";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}></ThemeProvider>
          <ReduxProvider>
            <ProtectedRoute>
              <NavBar />
              {children}
              <Toaster />
            </ProtectedRoute>
          </ReduxProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
